name: blue_challenge
description: "Blue challenge for the selection process."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  asp: ^1.3.0
  flutter_modular: ^6.3.4
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.3.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  shimmer: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app/icon.png"
  android: true
  ios: false
  fullscreen: true
  android_12:
    image: "assets/app/icon.png"
    image_dark: "assets/app/icon.png"
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    icon_background_color: "#FFFFFF"

flutter_icons:
  image_path: "assets/app/icon.png"
  ios: false
  android: "launcher_icon"
  adaptative_icon_background: "#FFFFFF"
  adaptative_icon_foreground: "assets/app/splash.png"

dev_dependencies:
  flutter_localizations:
    sdk: flutter

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
